### ISSUE TITLE
1284p optiboot compiled hex first line is useless and makes it incompatible with Nick Gammon's bootloader updater

### ISSUE THREAD

**Issue by liudr** [JChristensen/mighty-1284p#8]
As title says.

**Comment by JChristensen** [comment]
I'm not sure that "useless" is the same as "invalid"; AVRDUDE didn't have a problem with the extra 02 record. But it did seem to be an anomaly which went away when I recompiled. Not sure where it came from or why, I didn't spend any time looking into it. I'm not familiar with Nick's utility but if in fact the record is just useless rather than invalid, a code tweak may be appropriate.
